# Generated by Django 3.2.9 on 2021-11-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eknihy', '0002_auto_20211120_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='logo',
            field=models.ImageField(default='Logo.png', upload_to='books_covers'),
        ),
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.FileField(default='Book.pdf', upload_to='books'),
        ),
    ]
