# Generated by Django 3.2.9 on 2021-11-20 16:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Eknihy', '0005_alter_book_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eknihy.author', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum vytvoření'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='book',
            name='logo',
            field=models.ImageField(default='Logo.png', upload_to='books_covers', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])], verbose_name='Obrázek'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Název knihy'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(default='Book.pdf', upload_to='books', validators=[django.core.validators.FileExtensionValidator(['pdf', 'PDF'])], verbose_name='PDF'),
        ),
    ]
