# Generated by Django 3.2.9 on 2021-11-20 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Eknihy', '0006_auto_20211120_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum vytvoření'),
        ),
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Jméno'),
        ),
    ]
