# Generated by Django 3.2.9 on 2021-11-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eknihy', '0007_auto_20211120_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year_Of_Maturation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200, verbose_name='Roky maturity xxxx až xxxx')),
            ],
            options={
                'verbose_name': 'Rok maturity',
                'verbose_name_plural': 'Roky maturit',
            },
        ),
    ]
