# Generated by Django 3.2.9 on 2021-11-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eknihy', '0008_year_of_maturation'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='maturity',
            field=models.ManyToManyField(to='Eknihy.Year_Of_Maturation'),
        ),
    ]
