# Generated by Django 3.2.9 on 2021-11-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eknihy', '0009_book_maturity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Year_Of_Maturation',
            new_name='YearOfMaturation',
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='Popis'),
        ),
    ]
