# Generated by Django 3.2.9 on 2021-11-20 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eknihy', '0010_auto_20211120_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='logo',
            field=models.ImageField(upload_to='books_covers', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])], verbose_name='Obrázek'),
        ),
        migrations.AlterField(
            model_name='book',
            name='maturity',
            field=models.ManyToManyField(to='Eknihy.YearOfMaturation', verbose_name='Roky maturit'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(upload_to='books', validators=[django.core.validators.FileExtensionValidator(['pdf', 'PDF'])], verbose_name='PDF'),
        ),
    ]
