# Generated by Django 3.2.9 on 2021-11-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eknihy', '0011_auto_20211120_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('poezie', 'poezie'), ('próza', 'próza'), ('drama', 'drama')], default='próza', max_length=200, verbose_name='Žánr'),
        ),
        migrations.AddField(
            model_name='book',
            name='season',
            field=models.CharField(choices=[('literatura do konce 18. století', 'literatura do konce 18. století'), ('literatura do konce 19. století', 'literatura do konce 19. století'), ('světová literatura 20. a 21. století', 'světová literatura 20. a 21. století'), ('česká literatura 20. a 21. století', 'česká literatura 20. a 21. století')], default='', max_length=200, verbose_name='Období'),
        ),
    ]
