# Generated by Django 3.2.9 on 2021-12-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eknihy', '0012_auto_20211120_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['full_name'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autoři'},
        ),
        migrations.AlterModelOptions(
            name='yearofmaturation',
            options={'ordering': ['date'], 'verbose_name': 'Rok maturity', 'verbose_name_plural': 'Roky maturit'},
        ),
        migrations.AlterField(
            model_name='book',
            name='season',
            field=models.CharField(choices=[('literatura do konce 18. století', 'literatura do konce 18. století'), ('literatura do konce 19. století', 'literatura do konce 19. století'), ('světová literatura 20. a 21. století', 'světová literatura 20. a 21. století'), ('česká literatura 20. a 21. století', 'česká literatura 20. a 21. století')], default='světová literatura 20. a 21. století', max_length=200, verbose_name='Období'),
        ),
    ]
